export const moods = [
    'depressed',
    'energetic',
    'happy',
    'bored',
    'relaxed',
    'anxious',
    'excited',
    'sad',
    'curious',
    'tired',
    'angry',
    'hopeful',
    'stressed',
    'in work mode',
]

export const gptModels = [
    "gpt-4",
    "text-davinci-003",
    "text-curie-001",
    "text-babbage-001",
    "text-ada-001",
    "gpt-3.5-turbo",
]

export const interestsJackson = [
    'rock',
    'blues',
    'jazz',
    'country',
    'Drive-By Truckers',
    'Rolling Stones',
    'The Hives',
    'The Struts',
    'The Yeah Yeah Yeahs',
    'Can\t You Hear Me Knockin\'',
    'Gravity\'s Gone',
    'Shakin\''
]

export const interests = [
    'house music',
    'psychedelic trance',
    'goa',
    'blues',
    'jazz',
    'trap',
    'rap',
    'old school rap',
    'dubstep',
    'drum and bass',
    'R Stevie Moore',
    'Creedence Clearwater Revival',
    'Jimi Hendrix',
    'George Harrison',
    'Shakewell',
    'Fat Nick',
    'GERM',
    'Tyler the Creator',
    'Astral Projection',
    'Infected Mushroom',
    'A$AP Rocky',
    'Killer Mike',
    'Pendulum',
    'Animal Collective',
    'Interpol',
    'Passion Pit',
    'Tame Impala',
    'Kevin Parker',
    'Man With No Name',
    'Paul Oakenfold',
    'Metronomy',
]